### ISSUE TITLE
LLDB compatibility: pc register has to be lower-case

### ISSUE THREAD

**Issue by danlehmann** [daniel5151/gdbstub#155]
probe-rs (which uses gdbstub) was not compatible with lldb. I debugged the rootcause and it seems that lldb requires the `pc` register to be lower-case.

I sent a patch to probe-rs to make all registers lowercase: https://github.com/probe-rs/probe-rs/commit/5db3a46d3916f656bac61dbe91eb1352434fe02b which was just merged.

Still I wonder if gdbstub should maybe print a warning? Or itself make all registers lowercase so that users don't have to figure this out themselves?

Anyhow just an idea. Feel free to close if you feel this is not a good idea.

**Comment by daniel5151** [comment]
Unfortunately, `gdbstub` doesn't have any facilities for generating or parsing the XML files it transmits. It treats them all as opaque strings, and leaves the details of how to construct them up to the users of the library. It would be interesting if `gdbstub` could take a more hands-on role in generating / parsing XML data, but that's not something that is on the immediate roadmap. See #143 for more thoughts on the matter.

As such, there's no easy way to add this sort of "check that register names are lowercase" guard-rail / in-transit-modification at the `gdbstub` layer.

I'm going to close this out for now, not because it's a bad idea, but simply due to technical infeasibility at this time.

That said - this issue will be linked from #143, so it'll serve a useful role in motivating any future work in that space :)
